name: Bug Report
description: Something isn't working
labels: ["bug", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, .NET version, browser, SQL Server version, etc.
      placeholder: ".NET 8.0, Windows 11, SQL Server 2022, Chrome 133"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "high"
        - "medium"
        - "low"
    validations:
      required: true
