name: Story
description: User-facing feature or deliverable
labels: ["story", "triage"]
body:
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: "As a [role], I want [goal] so that [benefit]"
      placeholder: "As a user, I want to ..."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What must be true for this story to be complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any implementation guidance or constraints
      placeholder: "Consider using ..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "high"
        - "medium"
        - "low"
    validations:
      required: true
