name: Task
description: Implementation task (not user-facing)
labels: ["task", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true

  - type: textarea
    id: done-criteria
    attributes:
      label: Done Criteria
      description: How do we know this is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any relevant technical context

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "high"
        - "medium"
        - "low"
    validations:
      required: true
